# Generated by Django 4.0.4 on 2022-06-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelist_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='traveler',
        ),
    ]
