# Generated by Django 4.0.4 on 2022-06-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelist_api', '0002_rename_user_post_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(through='travelist_api.PostCategory', to='travelist_api.category'),
        ),
    ]
