# Generated by Django 4.0.4 on 2022-06-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelist_api', '0004_remove_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(through='travelist_api.PostCategory', to='travelist_api.category'),
        ),
    ]
