# Generated by Django 4.0.4 on 2022-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelist_api', '0005_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
