# Generated by Django 4.0.4 on 2022-06-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelist_api', '0009_bucketlist_traveledlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BucketList',
        ),
        migrations.DeleteModel(
            name='TraveledList',
        ),
    ]
