# Generated by Django 4.0.4 on 2022-06-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelist_api', '0010_delete_bucketlist_delete_traveledlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', through='travelist_api.PostCategory', to='travelist_api.category'),
        ),
    ]
