# Generated by Django 4.0.4 on 2022-06-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelist_api', '0012_bucketlist_traveledlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.URLField(max_length=10000),
        ),
    ]
